# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: true

runs:
  - id: 0
    type: script
    changes:
      wandb:
        name: CNN-0augs-LR=0.001
      general:
        batch_size: 32
        learning_rate: 0.001
        model_type: vit232
        epochs: 10
        patience: 10
        use_wandb: false
        use_kfold: false
        data_path: /app/src/datasets/UAV_Dataset_31
        # data_path: /app/src/datasets/static/31-augs-4-['time_stretch', 'sin_distortion']
        # data_path: /app/src/datasets/static/31-augs-1-time_stretch-sin_distortion
        # data_path: /app/src/datasets/static/9-augs-1-time_stretch-sin_distortion
        # save_dataloader: true
        save_dataloader: false
        num_classes: 31
        augmentations_per_sample: 0
 


  
  # Additional runs can be added following the same structure...
  # make sure to increment the id by 1 for each new run