# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, mert, vit
SEND_MESSAGE: true

runs:
# TODO update the config to work with new sweep :)
# TODO a script to make sure it works 
  - id: 10
    type: script
    changes:
      general:
        model_type: resnet18
        use_wandb: false
        use_sweep: false
        use_kfold: false
        data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
        num_classes: 31
        adapter_type: batchnorm
        sweep_count: 50
        epochs: 30
      sweep:
        project: resnet-experiments
        name: resnet18-batchnorm-0-augs
        method: random
        metric:
          name: test_acc
          goal: maximize
        parameters:
          target_modules:
          - batchnorm2d
          learning_rate:
            values:
            - 0.1
            - 0.01
            - 0.001
          
  # - id: 0
  #   type: sweep
  #   changes:
  #     general:
  #       model_type: resnet18
  #       use_wandb: true
  #       use_sweep: true
  #       use_kfold: false
  #       data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
  #       num_classes: 31
  #       adapter_type: batchnorm
  #       sweep_count: 50
  #       epochs: 30
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet18-batchnorm-0-augs
  #       method: random
  #       metric:
  #         name: test_acc
  #         goal: maximize
  #       parameters:
  #         target_modules:
  #         - batchnorm2d
  #         learning_rate:
  #           values:
  #           - 0.1
  #           - 0.01
  #           - 0.001
          
  # - id: 1
  #   type: sweep
  #   changes:
  #     general:
  #       model_type: resnet50
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet50-batchnorm-0-augs
  #       method: random

  # - id: 2
  #   type: sweep
  #   changes:
  #     general:
  #       model_type: resnet152
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet152-batchnorm-0-augs
  
  # - id: 3
  #   type: sweep
  #   changes:
  #     general:
  #       model_type: resnet18
  #       data_path: /app/src/datasets/static/31-augs-3-time_stretch-sin_distortion
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet18-batchnorm-3-augs

  # - id: 4
  #   type: sweep
  #   changes:
  #     general:
  #       model_type: resnet50
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet50-batchnorm-3-augs

  # - id: 5
  #   type: sweep
  #   changes:
  #     general:
  #       model_type: resnet152
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet152-batchnorm-3-augs
  
  # none-full sweeps
  # - id: 6
  #   type: sweep
  #   changes: 
  #     general:
  #       model_type: resnet18
  #       data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
  #       adapter_type: none-full
  #       epochs: 10
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet18-none-full-0-augs
  #       method: random
  #       metric:
  #         name: test_acc
  #         goal: maximize
  #       parameters:
  #         learning_rate:
  #           values:
  #           - 0.1
  #           - 0.01
  #           - 0.001
  #         seed:
  #           distribution: int_uniform
  #           min: 0
  #           max: 1000
  # - id: 7
  #   type: sweep
  #   changes: 
  #     general:
  #       model_type: resnet50
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet50-none-full-0-augs

  # - id: 8
  #   type: sweep
  #   changes: 
  #     general:
  #       model_type: resnet152
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet152-none-full-0-augs

  # - id: 9
  #   type: sweep
  #   changes: 
  #     general:
  #       model_type: resnet18
  #       data_path: /app/src/datasets/static/31-augs-3-time_stretch-sin_distortion
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet18-none-full-3-augs

  # - id: 10
  #   type: sweep
  #   changes: 
  #     general:
  #       model_type: resnet50
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet50-none-full-3-augs

  # - id: 11
  #   type: sweep
  #   changes: 
  #     general:
  #       model_type: resnet152
  #     sweep:
  #       project: resnet-experiments
  #       name: resnet152-none-full-3-augs

          
