services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    image: ast_container
    container_name: ast_script_container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
      - WANDB_API_KEY=${WANDB_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      # DDP configuration
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PL_TRAINER_STRATEGY=ddp
      - TORCH_DISTRIBUTED_DEBUG=INFO
      - NCCL_DEBUG=INFO
      - NCCL_SOCKET_IFNAME=eth0
      - NCCL_P2P_DISABLE=0
      - NCCL_IB_DISABLE=1
      - NCCL_BLOCKING_WAIT=1
      - TORCH_NCCL_ASYNC_ERROR_HANDLING=0  # Disable async error handling to fix pipe issues
      - WANDB_START_METHOD=thread
      - WANDB_AGENT_DISABLE_FLAPPING=true
      - MASTER_ADDR=localhost
      - MASTER_PORT=12355
      - TORCH_CPP_LOG_LEVEL=INFO
      - TORCH_SHOW_CPP_STACKTRACES=1
      - PYTHONPATH=/app
      # Separate processes settings
      - WORLD_SIZE=2  # Total number of processes
      - NODE_RANK=0   # Current node rank

    volumes:
      - ./src:/app/src
      - ./src/datasets/.:/app/src/datasets
      - ./src/model_cache:/app/src/model_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    # Use torchrun instead of the deprecated torch.distributed.launch
    command: python -m torch.distributed.run --nproc_per_node=2 --master_port=12355 sweeps.py
    
    # Alternative command for non-DDP execution
    # command: python sweeps.py
    
    stdin_open: true
    tty: true
    working_dir: /app/src
    user: root
    networks:
      - app_network
    shm_size: 16gb
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    healthcheck:
      test: ["CMD", "nvidia-smi"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  datasets:
    driver: local
  src:
  model_cache:

networks:
  app_network:
    driver: bridge

# Add a .env file with the following content to set default compose options
# COMPOSE_COMMAND_OPTIONS=--remove-orphans