services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    image: ast_container
    container_name: ast_script_container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
      - WANDB_API_KEY=${WANDB_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PL_TRAINER_STRATEGY=ddp
      - TORCH_DISTRIBUTED_DEBUG=DETAIL
      - NCCL_DEBUG=INFO
      - NCCL_SOCKET_IFNAME=eth0
      - NCCL_P2P_DISABLE=0
      - NCCL_IB_DISABLE=1
      - WANDB_START_METHOD=thread

    volumes:
      - ./src:/app/src  # Only mount the src directory as read-only
      - ./src/datasets/.:/app/src/datasets
      - ./src/model_cache:/app/src/model_cache  # Mount the model_cache directory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    # command: python3 script.py
    command: python3 main.py
    # command: python3 sweeps.py
    # command: /bin/bash # interactive shell new
    stdin_open: true
    tty: true
    working_dir: /app/src
    user: root
    networks:
      - app_network
    shm_size: 8gb  # Shared memory size for DDP communication
    ipc: host  # Add host IPC namespace for better shared memory performance
    ulimits:  # Increase ulimits for NCCL communication
      memlock: -1
      stack: 67108864

volumes:
  datasets:
    driver: local
  src:
  model_cache:

networks:
  app_network:
    driver: bridge

# Add a .env file with the following content to set default compose options
# COMPOSE_COMMAND_OPTIONS=--remove-orphans