services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    image: ast_script
    container_name: ast_script_container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
      - WANDB_API_KEY=${WANDB_API_KEY}  # Changed to WANDB_API_KEY
    volumes:
      - ./src:/app/src:ro  # Only mount the src directory as read-only
      - C:/Users/Sidewinders/Desktop/CODE/UAV_Classification_repo/src/.datasets:/app/src/.datasets:ro
      # - /Users/applefella/Desktop/UAV_project/UAV_Classification/src/.datasets:/app/src/.datasets:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python3 script.py
    # command: python3 sweeps.py
    # command: /bin/bash # interactive shell
    stdin_open: true
    tty: true
    working_dir: /app/src  # Change this to /app/src
    user: "appuser"
    networks:
      - app_network

volumes:
  datasets:
    driver: local
  src:  # Add this named volume

networks:
  app_network:
    driver: bridge