services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    image: ast_container
    container_name: ast_script_container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
      - WANDB_API_KEY=${WANDB_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}

    volumes:
      - ./src:/app/src  # Only mount the src directory as read-only
      - ./src/datasets/.:/app/src/datasets
      - ./src/model_cache:/app/src/model_cache  # Mount the model_cache directory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python3 train_cnn.py
    # command: python3 script.py
    # command: python3 sweeps.py
    # command: /bin/bash # interactive shell new
    stdin_open: true
    tty: true
    working_dir: /app/src  # Change this to /app/src
    # user: "appuser"
    user: root
    networks:
      - app_network

volumes:
  datasets:
    driver: local
  src:  # Add this named volume
  model_cache:  # Add this named volume

networks:
  app_network:
    driver: bridge