general:
  data_path: /app/src/datasets/UAV_Dataset_31
  num_classes: 31
  save_dataloader: false
  model_type: vit232
  batch_size: 32
  seed: 42
  num_cuda_workers: 10
  pinned_memory: true
  epochs: 10
  save_model: false
  test_size: 0.2
  inference_size: 0.1
  val_size: 0.1
  shuffled: false
  sweep_count: 200
  accumulation_steps: 2
  learning_rate: 0.001
  patience: 10
  use_wandb: false
  torch_viz: false
  use_kfold: false
  k_folds: 5

cnn_config:
  hidden_units: 256
  feature_extraction:
    type: melspectrogram
    sampling_rate: 16000
    n_mfcc: 40
    n_mels: 128
    n_fft: 1024
    hop_length: 512
    power: 2