general:
  model_type: efficientnet_b0
  batch_size: 48
  seed: 42
  num_cuda_workers: 10
  pinned_memory: true
  epochs: 20
  save_model: false
  test_size: 0.2
  inference_size: 0
  val_size: 0.1
  sweep_count: 50
  accumulation_steps: 1
  patience: 5
  use_wandb: true
  use_sweep: true
  torch_viz: false
  use_kfold: false
  k_folds: 5
  adapter_type: none-full
  save_dataloader: false
  monitor: val_acc
  mode: max
  distributed_training: true
  num_gpus: 2
  strategy: ddp
optimizer:
  optimizer_type: adamw
  adam:
    lr: 1e-4
    betas:
    - 0.99
    - 0.999
  adamw:
    lr: 0.0001
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.999
  warmup:
    enabled: false
    warmup_steps: 100
    warmup_start_lr: 1e-6
    warmup_method: linear
  scheduler_type: reduce_lr_on_plateau
  cosine_annealing_lr:
    T_max: 50
    eta_min: 0.0
  reduce_lr_on_plateau:
    mode: max
    factor: 0.85
    patience: 3
  gradient_clip_val: 10.0
  gradient_clip_algorithm: norm
dataset:
  dataset_type: esc50
  data_path: ./datasets/ESC-50-master/classes
  num_classes: 50
  target_sr: 16000
  target_duration: 5
  file_extension: .wav
augmentations:
  augmentations_per_sample: 3
  augmentations:
  - gaussian_noise
  - time_mask
  - polarity_inversion
  sin_distortion_min_rate: 0.1
  sin_distortion_max_rate: 0.6
  sin_distortion_p: 0.9
  polarity_inversion_p: 0.8
  gaussian_noise_min_amplitude: 0.1
  gaussian_noise_max_amplitude: 0.15
  gaussian_noise_p: 0.8
  time_mask_min_band_part: 0.01
  time_mask_max_band_part: 0.15
  time_mask_fade_duration: 0.01
  time_mask_p: 0.8
feature_extraction:
  type: melspectrogram
  sampling_rate: 16000
  n_mfcc: 40
  n_mels: 128
  n_fft: 2048
  hop_length: 200
  power: 2
none-classifier:
  task_type: AUDIO_CLASSIFICATION
none-full:
  task_type: AUDIO_CLASSIFICATION
lora:
  r: 8
  lora_alpha: 16
  target_modules:
  - key
  - value
  - query
  - dense
  lora_dropout: 0
  bias: lora_only
ia3:
  feedforward_modules:
  - key
  - value
  - query
  - dense
  target_modules:
  - key
  - value
  - query
  - dense
adalora:
  init_r: 4
  target_r: 256
  target_modules:
  - key
  - value
  - query
  - dense
  lora_alpha: 4
oft:
  r: 128
  target_modules:
  - key
  - value
  - query
  - dense
  module_dropout: 0.2
  init_weights: true
layernorm:
  target_modules:
  - layernorm_before
  - layernorm_after
  task_type: AUDIO_CLASSIFICATION
hra:
  r: 2
  target_modules:
  - key
  - value
  - query
  - dense
ssf:
  init_scale: 1.0
  init_shift: 0.5
  target_modules:
  - linear
  - dense
  - batchnorm2d
  - conv2d
batchnorm:
  target_modules:
  - batchnorm2d
lorac:
  target_modules:
  - linear
  - conv2d
  - batchnorm2d
  r: 4
  alpha: 8
  dropout: 0
bitfit:
  trainable_components:
  - bias
wandb:
  project: ast-esc50-optimization
  name: ast-baseline-conservative-b48-lr1e4
  reinit: true
  notes: null
  tags:
  - ast
  - esc50
  - baseline
  - conservative
  - kfold
  - none-classifier
  - batch48
  - lr1e-4
  dir: wandb
sweep:
  project: new-sweeps-test-5-31
  name: nothing-burder
  method: random
  metric:
    name: val_acc
    goal: maximize
  parameters:
    batch_size:
      values:
      - 16
      - 32
      - 48
      - 64