general:
  model_type: ast
  from_scratch: false
  batch_size: 2
  seed: 42
  num_cuda_workers: 2
  pinned_memory: true
  epochs: 20
  save_model: false
  test_size: 0.0
  inference_size: 0.0
  val_size: 0.2
  sweep_count: 200
  accumulation_steps: 1
  patience: 5
  use_wandb: false
  use_sweep: false
  torch_viz: false
  use_kfold: false
  k_folds: 5
  adapter_type: none-full
  save_dataloader: false
  monitor: val_acc
  mode: max
  distributed_training: false
  num_gpus: 1
  strategy: ddp
  compute_fisher: true
  fisher_mc_samples: 100
  save_fim_heatmap: true
  save_fim_epochs: true
peft_scheduling:
  enabled: false
  auto_merge: true
  schedule:
  - start_epoch: 1
    peft_method: none-classifier
  - start_epoch: 2
    peft_method: none-full
    merge_previous: true
  - start_epoch: 3
    peft_method: ia3
    merge_previous: true
optimizer:
  optimizer_type: adam
  adam:
    lr: 1e-4
    betas:
    - 0.99
    - 0.999
  adamw:
    lr: 0.0008
    weight_decay: 0.02
    betas:
    - 0.99
    - 0.999
  adamspd:
    lr: 1e-4
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.999
    eps: 1e-8
    amsgrad: false
  warmup:
    enabled: true
    warmup_steps: 100
    warmup_start_lr: 1e-6
    warmup_method: linear
  scheduler_type: cosine_annealing_lr
  cosine_annealing_lr:
    T_max: 50
    eta_min: 0.0
  reduce_lr_on_plateau:
    mode: max
    factor: 0.85
    patience: 3
  gradient_clipping_enabled: true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
loss:
  type: cross_entropy
  label_smoothing: 0.1  # Valid range: 0.0 (no smoothing) to 1.0 (maximum smoothing). Recommended: 0.1-0.3
  class_weights: null  # Optional: [1.0, 1.0, 1.0] for balanced classes or custom weights for imbalanced datasets
dataset:
  # dataset_type: esc10
  # data_path: datasets/ESC-10-master/classes
  dataset_type: uav
  data_path: datasets/UAV_Dataset_31
augmentations:
  augmentations_per_sample: 0
  augmentations:
  - time_mask
  - time_stretch
  - sin_distortion
  sin_distortion_min_rate: 0.1
  sin_distortion_max_rate: 0.6
  sin_distortion_p: 0.9
  polarity_inversion_p: 0.8
  gaussian_noise_min_amplitude: 0.1
  gaussian_noise_max_amplitude: 0.15
  gaussian_noise_p: 0.8
  time_mask_min_band_part: 0.01
  time_mask_max_band_part: 0.15
  time_mask_fade_duration: 0.01
  time_mask_p: 0.8
feature_extraction:
  type: melspectrogram
  sampling_rate: 16000
  n_mfcc: 40
  n_mels: 128
  n_fft: 1024
  hop_length: 128
  power: 2
none-classifier:
  task_type: AUDIO_CLASSIFICATION
none-full:
  task_type: AUDIO_CLASSIFICATION
lora:
  r: 8
  lora_alpha: 16
  target_modules:
  - key
  - value
  - query
  - dense
  lora_dropout: 0.1
  bias: lora_only
ia3:
  feedforward_modules:
  - key
  - value
  - query
  - dense
  target_modules:
  - key
  - value
  - query
  - dense
adalora:
  init_r: 8
  target_r: 256
  target_modules:
  - key
  - value
  - query
  - dense
  lora_alpha: 4
oft:
  r: 128
  target_modules:
  - key
  - value
  - query
  - dense
  module_dropout: 0.2
  init_weights: true
layernorm:
  target_modules:
  - layernorm1
  - layernorm2
  task_type: AUDIO_CLASSIFICATION
hra:
  r: 2
  target_modules:
  - key
  - value
  - query
  - dense
ssf:
  init_scale: 1.0
  init_shift: 0.5
  target_modules:
  - linear
  - dense
  - batchnorm2d
batchnorm:
  target_modules:
  - batchnorm2d
lorac:
  target_modules:
  - linear
  - conv2d
  - batchnorm2d
  r: 4
  alpha: 8
  dropout: 0
bitfit:
  trainable_components:
  - bias
wandb:
  project: esc50-ast-peft-baselines
  name: ast-oft
  reinit: true
  notes: null
  tags:
  - vit-base
  dir: wandb
sweep:
  project: sweep-esc50
  name: resnet18-peft-schedule-sweep
  method: random
  metric:
    name: test_acc
    goal: maximize
  parameters:
    peft_scheduling.schedule.0.start_epoch:
      values:
      - 0
    peft_scheduling.schedule.0.peft_method:
      values:
      - none-classifier
      - lorac
      - ssf
      - none-full
      - batchnorm
      - bitfit
    peft_scheduling.schedule.1.start_epoch:
      values:
      - 5
    peft_scheduling.schedule.1.peft_method:
      values:
      - none-classifier
      - lorac
      - ssf
      - none-full
      - batchnorm
      - bitfit
    peft_scheduling.schedule.2.start_epoch:
      values:
      - 10
    peft_scheduling.schedule.2.peft_method:
      values:
      - none-classifier
      - lorac
      - ssf
      - none-full
      - batchnorm
      - bitfit
    peft_scheduling.schedule.3.start_epoch:
      values:
      - 15
    peft_scheduling.schedule.3.peft_method:
      values:
      - none-classifier
      - lorac
      - ssf
      - none-full
      - batchnorm
      - bitfit

# -----------------------------------------------------------------------------------
# Ensemble configuration
# -----------------------------------------------------------------------------------
ensemble:
  enabled: false  # Set to true to activate ensemble mode
  size: 1         # Constant M – number of models in the ensemble (M=1 → no ensemble)
  same_minibatch: true  # true = each model sees same mini-batch, false = different mini-batches
