general:
  data_path: /app/src/datasets/UAV_Dataset_9
  num_classes: 9
  save_dataloader: false
  model_type: mert
  batch_size: 16
  seed: 42
  num_cuda_workers: 10
  pinned_memory: true
  epochs: 10
  save_model: false
  test_size: 0.2
  inference_size: 0.1
  val_size: 0.1
  sweep_count: 200
  accumulation_steps: 2
  learning_rate: 0.002
  patience: 10
  use_wandb: true
  use_sweep: true
  torch_viz: false
  use_kfold: false
  k_folds: 5
  adapter_type: none-full
augmentations:
  augmentations_per_sample: 0
  augmentations:
  - time_stretch
  - sin_distortion
  time_stretch_min_rate: 0.9
  time_stretch_max_rate: 1.0
  sin_distortion_min_rate: 0.01
  sin_distortion_max_rate: 0.7
  sin_distortion_p: 1
feature_extraction:
  type: melspectrogram
  sampling_rate: 16000
  n_mfcc: 40
  n_mels: 128
  n_fft: 1024
  hop_length: 512
  power: 2
none-classifier:
  task_type: AUDIO_CLASSIFICATION
none-full:
  task_type: AUDIO_CLASSIFICATION
lora:
  r: 8
  lora_alpha: 16
  target_modules:
  - query
  - key
  - value
  - dense
  lora_dropout: 0
  bias: lora_only

ia3:
  target_modules:
  - query
  - key
  - value
  - dense
  feedforward_modules:
  - dense
  - query
  - key
  - value

adalora:
  init_r: 32
  target_r: 16
  target_modules:
  - query
  - key
  - value
  - dense
  lora_alpha: 8

oft:
  r: 768
  target_modules:
  - query
  - key
  - value
  - dense
  module_dropout: 0.0
  init_weights: true
layernorm:
  target_modules:
  - layernorm
  task_type: AUDIO_CLASSIFICATION
hra:
  r: 8
  target_modules:
  - query
  - key
  - value
  - dense
  # task_type: AUDIO_CLASSIFICATION
wandb:
  project: model-full-test
  name: mert
  reinit: true
  notes: null
  tags: null
  dir: wandb
sweep:
  project: demo-ddp
  name: test1
  method: random
  metric:
    name: test_acc
    goal: maximize
  parameters:
    seed:
      values:
      - 42
      - 43
      - 44
      - 45
      - 46
    learning_rate:
      values:
      - 0.001
      - 0.002
      - 0.003
      - 0.004
