general:
  data_path: /app/src/datasets/UAV_Dataset_9
  # data_path: /app/src/datasets/UAV_Dataset_31
  # data_path: /Users/Sidewinders/Desktop/CODE/UAV_Classification_repo/.datasets/UAV_Dataset_9
  # data_path: /Users/Sidewinders/Desktop/CODE/UAV_Classification_repo/.datasets/static-31-augs-1-time_stretch-sin_distortion
  # data_path: /Users/applefella/Documents/UAV_Classification/UAV_Classification/.datasets/UAV_Dataset_9
  num_classes: 9
  save_dataloader: false
  model_type: resnet18
  batch_size: 32
  seed: 42
  num_cuda_workers: 10
  pinned_memory: true
  epochs: 10
  save_model: false
  test_size: 0.2
  inference_size: 0.1
  val_size: 0.1
  sweep_count: 200
  accumulation_steps: 2
  learning_rate: 0.001
  patience: 10
  use_wandb: true
  torch_viz: false
  use_kfold: false
  k_folds: 5
  adaptor_type: none-classifier

augmentations:
  augmentations_per_sample: 1
  augmentations:
  - time_stretch
  - sin_distortion
  time_stretch_min_rate: 0.9
  time_stretch_max_rate: 1.0
  sin_distortion_min_rate: 0.01
  sin_distortion_max_rate: 0.7
  sin_distortion_p: 1

cnn_config:
  hidden_units: 256
  feature_extraction:
    type: melspectrogram
    sampling_rate: 16000
    n_mfcc: 40
    n_mels: 128
    n_fft: 1024
    hop_length: 512
    power: 2


lora:
  r: 1000
  lora_alpha: 16
  target_modules:
  - query
  - key
  - value
  - dense
  lora_dropout: 0
  bias: lora_only
  task_type: AUDIO_CLASSIFICATION
  use_rslora: false
  use_dora: false
ia3:
  target_modules:
  - query
  - key
  - value
  - dense
  feedforward_modules:
  - dense
  - query
  - key
  - value
  task_type: AUDIO_CLASSIFICATION
adalora:
  init_r: 100
  target_r: 16
  target_modules:
  - query
  - key
  - value
  - dense
  lora_alpha: 8
  task_type: AUDIO_CLASSIFICATION
oft:
  r: 768
  target_modules:
  - query
  - key
  - value
  - dense
  module_dropout: 0.0
  init_weights: true
fourier:
  scaling: 100
  n_frequency: 1000
  target_modules:
  - query
  - key
  - value
  - dense
  task_type: AUDIO_CLASSIFICATION
layernorm:
  target_modules:
  - layernorm
  task_type: AUDIO_CLASSIFICATION


wandb:
  project: demo-plt
  name: test-1
  reinit: false
  notes: null
  tags: null
  dir: wandb
sweep:
  name: demo-plt/Sweep
  method: random
  metric:
    name: test_acc
    goal: maximize
  parameters:
    augmentations_per_sample:
      values:
      - 1
      - 2
      - 3
      - 4
      - 5
    num_augmentations:
      values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5