general:
  data_path: /app/src/datasets/UAV_Dataset_9
  num_classes: 9
  save_dataloader: false
  model_type: mobilenet_v3_small
  batch_size: 4
  seed: 42
  num_cuda_workers: 10
  pinned_memory: true
  epochs: 2
  save_model: false
  test_size: 0.2
  inference_size: 0.1
  val_size: 0.1
  sweep_count: 200
  accumulation_steps: 2
  learning_rate: 0.02
  patience: 10
  use_wandb: false
  use_sweep: true
  torch_viz: false
  use_kfold: false
  k_folds: 5
  adapter_type: lorac
augmentations:
  augmentations_per_sample: 0
  augmentations:
  - time_stretch
  - sin_distortion
  time_stretch_min_rate: 0.9
  time_stretch_max_rate: 1.0
  sin_distortion_min_rate: 0.01
  sin_distortion_max_rate: 0.7
  sin_distortion_p: 1
feature_extraction:
  type: melspectrogram
  sampling_rate: 16000
  n_mfcc: 40
  n_mels: 128
  n_fft: 1024
  hop_length: 512
  power: 2
none-classifier:
  task_type: AUDIO_CLASSIFICATION
none-full:
  task_type: AUDIO_CLASSIFICATION
lora:
  r: 8
  lora_alpha: 16
  target_modules:
  - key
  - value
  - query
  lora_dropout: 0
  bias: lora_only
ia3:
  feedforward_modules:
  - key
  - value
  - query
  target_modules:
  - key
  - value
  - query
adalora:
  init_r: 32
  target_r: 16
  target_modules:
  - key
  - value
  - query
  lora_alpha: 8
oft:
  r: 768
  target_modules:
  - key
  - value
  - query
  module_dropout: 0.0
  init_weights: true
layernorm:
  target_modules:
  - layernorm_before
  - layernorm_after
  task_type: AUDIO_CLASSIFICATION
hra:
  r: 4
  target_modules:
  - key
  - value
  - query
ssf:
  init_scale: 1.0
  init_shift: 0.0
  target_modules:
  - linear
  - conv2d
  - batchnorm2d
batchnorm:
  target_modules:
  - batchnorm2d
lorac:
  target_modules:
  - linear
  - conv2d
  - batchnorm2d
  r: 8
  alpha: 8
  dropout: 0
bitfit:
  trainable_components:
  - bias
wandb:
  project: model-peft-test
  name: mert-none-classifier
  reinit: true
  notes: null
  tags: null
  dir: wandb
sweep:
  project: demo-ddp
  name: test1
  method: random
  metric:
    name: test_acc
    goal: maximize
  parameters:
    seed:
      values:
      - 42
      - 43
      - 44
      - 45
      - 46
    learning_rate:
      values:
      - 0.001
      - 0.002
      - 0.003
      - 0.004
