general:
  model_type: resnet50
  from_scratch: false
  batch_size: 32
  seed: 42
  num_cuda_workers: 5
  pinned_memory: true
  epochs: 90
  save_model: false
  test_size: 0.0
  inference_size: 0.0
  val_size: 0.2
  sweep_count: 9
  accumulation_steps: 1
  patience: 15
  use_wandb: false
  use_sweep: false
  torch_viz: false
  use_kfold: false
  k_folds: 5
  adapter_type: none-full
  save_dataloader: false
  monitor: val_acc
  mode: max
  distributed_training: false
  num_gpus: 1
  strategy: ddp
  compute_fisher: false
  fisher_mc_samples: 100
  save_fim_heatmap: true
  save_fim_epochs: true
peft_scheduling:
  enabled: false
  auto_merge: true
  schedule:
  - start_epoch: 1
    peft_method: none-classifier
  - start_epoch: 2
    peft_method: none-full
    merge_previous: true
  - start_epoch: 3
    peft_method: ia3
    merge_previous: true
optimizer:
  optimizer_type: sgd
  adam:
    lr: 1e-8
    betas:
    - 0.99
    - 0.999
  adamw:
    lr: 1e-4
    weight_decay: 1e-3
    betas:
    - 0.99
    - 0.999
  adamspd:
    lr: 1e-8
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.999
    eps: 1e-8
    amsgrad: false
  sgd:
    lr: 1e-4
    momentum: 0.9
    weight_decay: 1e-3
    nesterov: false
  warmup:
    enabled: false
    warmup_steps: 100
    warmup_start_lr: 1e-6
    warmup_method: linear
  scheduler_type: step_lr
  cosine_annealing_lr:
    T_max: 50
    eta_min: 0.0
  reduce_lr_on_plateau:
    mode: min
    factor: 0.1
    patience: 10
  StepLRConfig:
    step_size: 30
    gamma: 0.1
  gradient_clipping_enabled: true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
loss:
  type: cross_entropy
  label_smoothing: 0.1
  class_weights: null
dataset:
  dataset_type: esc50
  data_path: datasets/ESC-50-master/classes
augmentations:
  augmentations_per_sample: 0
  augmentations:
    - time_mask
    - time_stretch
  
feature_extraction:
  type: melspectrogram
  sampling_rate: 44100
  n_mfcc: 40
  n_mels: 128
  n_fft: 1024
  hop_length: 128
  power: 2
none-classifier:
  task_type: AUDIO_CLASSIFICATION
none-full:
  task_type: AUDIO_CLASSIFICATION
lora:
  r: 8
  lora_alpha: 16
  target_modules:
  - key
  - value
  - query
  - dense
  lora_dropout: 0.1
  bias: lora_only
ia3:
  feedforward_modules:
  - key
  - value
  - query
  - dense
  target_modules:
  - key
  - value
  - query
  - dense
adalora:
  init_r: 8
  target_r: 256
  target_modules:
  - key
  - value
  - query
  - dense
  lora_alpha: 4
oft:
  r: 128
  target_modules:
  - key
  - value
  - query
  - dense
  module_dropout: 0.2
  init_weights: true
layernorm:
  target_modules:
  - layernorm1
  - layernorm2
  task_type: AUDIO_CLASSIFICATION
hra:
  r: 2
  target_modules:
  - key
  - value
  - query
  - dense
ssf:
  init_scale: 1.0
  init_shift: 0.5
  target_modules:
  - linear
  - dense
  - batchnorm2d
  - conv2d
batchnorm:
  target_modules:
  - batchnorm2d
lorac:
  target_modules:
  - linear
  - conv2d
  - batchnorm2d
  r: 4
  alpha: 8
  dropout: 0
bitfit:
  trainable_components:
  - bias
wandb:
  project: esc50-resnet-deep-ensemble
  name: resnet50-m4-ssf
  reinit: true
  notes: null
  tags:
  - ensemble
  dir: wandb
sweep:
  project: pretrained-scratch-sweeps
  name: esc50_custom_cnn
  method: grid
  metric:
    name: val_acc
    goal: maximize
  parameters:
    optimizer.adamw.lr:
      values:
      - 1e-4
      - 1e-3
      - 1e-2
    loss.label_smoothing:
      values:
      - 0.0
      - 0.1
      - 0.2
ensemble:
  enabled: false
  size: 4
  same_minibatch: false
spectrogram3ch:
  window_sizes_ms: [25, 50, 100]
  hop_sizes_ms: [10, 25, 50]
  n_mels: 128
  n_fft: 44100
  target_width: 250
  eps: 1.0e-6
