# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, mert, vit
SEND_MESSAGE: true

runs:
# TODO update the config to work with new sweep :)
# TODO a script to make sure it works 
  # - id: 10
  #   type: script
  #   changes:
  #     general:
  #       model_type: efficientnet_b0
  #       use_wandb: false
  #       use_sweep: false
  #       use_kfold: false
  #       data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
  #       num_classes: 31
  #       adapter_type: lorac
  #       sweep_count: 50
  #       epochs: 30
      # sweep:
      #   project: efficientnet-experiments
      #   name: efficientnet_b0-lorac-0-augs
      #   method: random
      #   metric:
      #     name: test_acc
      #     goal: maximize
      #   parameters:
      #     # TODO add hyperparameters
          
  - id: 0
    type: sweep
    changes:
      general:
        model_type: efficientnet_b0
        use_wandb: true
        use_sweep: true
        use_kfold: false
        data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
        num_classes: 31
        adapter_type: lorac
        sweep_count: 50
        epochs: 30
      sweep:
        project: efficientnet-experiments
        name: efficientnet_b0-lorac-0-augs
        method: random
        metric:
          name: test_acc
          goal: maximize
        parameters:
          target_modules:
            values:
            - [linear, conv2d, batchnorm2d]
            - [conv2d, batchnorm2d]
            - [batchnorm2d]
            - [conv2d]
          r:
            values:
            - 8
            - 16
            - 4
            - 32
          alpha:
            values: 
            - 8
            - 16
            - 32
            - 4
          dropout:
            values:
            - 0.1
            - 0
            - 0.2
          
  - id: 1
    type: sweep
    changes:
      general:
        model_type: efficientnet_b4
      sweep:
        name: efficientnet_b4-lorac-0-augs

  - id: 2
    type: sweep
    changes:
      general:
        model_type: efficientnet_b7
      sweep:
        name: efficientnet_b7-lorac-0-augs
  
  - id: 3
    type: sweep
    changes:
      general:
        model_type: efficientnet_b0
        data_path: /app/src/datasets/static/31-augs-3-time_stretch-sin_distortion
      sweep:
        name: efficientnet_b0-lorac-3-augs

  - id: 4
    type: sweep
    changes:
      general:
        model_type: efficientnet_b4
      sweep:
        name: efficientnet_b4-lorac-3-augs

  - id: 5
    type: sweep
    changes:
      general:
        model_type: efficientnet_b7
      sweep:
        name: efficientnet_b7-lorac-3-augs
  