# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over
# AST runs optimized for ESC-50 small dataset based on research findings

SEND_MESSAGE: true

runs:
  # Run 1: Conservative AST baseline - proven configuration from paper
  - id: 1
    type: script
    changes:
      general:
        model_type: vit-base  # EfficientNet-B0 is a good baseline for ESC-50
        monitor: val_acc
        mode: max
      peft_scheduling:
        enabled: true
        schedule:
        - start_epoch: 0
          peft_method: none-full
        - start_epoch: 10
          peft_method: none-classifier
  - id: 2
    type: script
    changes:
      general:
        model_type: vit-base  # EfficientNet-B0 is a good baseline for ESC-50
        monitor: train_acc
        mode: max
      peft_scheduling:
        enabled: true
        schedule:
        - start_epoch: 0
          peft_method: none-full
        - start_epoch: 15
          peft_method: none-classifier
  - id: 3
    type: script
    changes:
      general:
        model_type: vit-base  # EfficientNet-B0 is a good baseline for ESC-50
        monitor: train_loss
        mode: min
      peft_scheduling:
        enabled: true
        schedule:
        - start_epoch: 0
          peft_method: none-full
        - start_epoch: 20
          peft_method: none-classifier
  - id: 4
    type: script
    changes:
      general:
        model_type: vit-base  # EfficientNet-B0 is a good baseline for ESC-50
        monitor: val_loss
        mode: min
      peft_scheduling:
        enabled: true
        schedule:
        - start_epoch: 0
          peft_method: none-classifier
        - start_epoch: 10
          peft_method: none-full
  - id: 5
    type: script
    changes:
      general:
        model_type: vit-base  # EfficientNet-B0 is a good baseline for ESC-50
      peft_scheduling:
        enabled: true
        schedule:
        - start_epoch: 0
          peft_method: none-classifier
        - start_epoch: 15
          peft_method: none-full
  - id: 6
    type: script
    changes:
      general:
        model_type: vit-base  # EfficientNet-B0 is a good baseline for ESC-50
      peft_scheduling:
        enabled: true
        schedule:
        - start_epoch: 0
          peft_method: none-classifier
        - start_epoch: 20
          peft_method: none-full
        

