# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: true

runs:
  - id: 0
    type: script
    changes:
      wandb:
        name: testing-main-1
      general:
        use_sweep: false
        use_wandb: false
        model_type: resnet18
        data_path: /app/src/datasets/UAV_Dataset_9
  - id: 1
    type: script
    changes:
      wandb:
        name: testing-main-2
      general:
        use_sweep: false
        use_wandb: false
        model_type: resnet34
        data_path: /app/src/datasets/UAV_Dataset_31

 


  
  # Additional runs can be added following the same structure...
  # make sure to increment the id by 1 for each new run