# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: true


runs:
  - id: 4
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: true
        use_sweep: false
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31
        adapter_type: ssf
        k_folds: 5
        learning_rate: 0.001
        batch_size: 8
        epochs: 20
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      augmentations:
        augmentations_per_sample: 0
      wandb:
        project: 31-class-kfold
        name: efficientnet_b7-ssf-0-augs-RERUN
        reinit: true
        tags:
          - 31-class
          - kfold
          - efficientnet_b7
          - ssf
          - 0-augs
          - RERUN
  - id: 5
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: true
        use_sweep: false
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31
        adapter_type: batchnorm
        k_folds: 5
        learning_rate: 0.001
        batch_size: 8
        epochs: 20
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      augmentations:
        augmentations_per_sample: 0
      wandb:
        project: 31-class-kfold
        name: efficientnet_b7-batchnorm-0-augs-RERUN
        reinit: true
        tags:
          - 31-class
          - kfold
          - efficientnet_b7
          - batchnorm
          - 0-augs
          - RERUN
  - id: 6
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: true
        use_sweep: false
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31
        adapter_type: none-classifier
        k_folds: 5
        learning_rate: 0.001
        batch_size: 8
        epochs: 20
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      augmentations:
        augmentations_per_sample: 0
      wandb:
        project: 31-class-kfold
        name: efficientnet_b7-none-classifier-0-augs-RERUN
        reinit: true
        tags:
          - 31-class
          - kfold
          - efficientnet_b7
          - none-classifier
          - 0-augs
          - RERUN
  - id: 7
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: true
        use_sweep: false
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31
        adapter_type: none-full
        k_folds: 5
        learning_rate: 0.001
        batch_size: 8
        epochs: 20
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      augmentations:
        augmentations_per_sample: 0
      wandb:
        project: 31-class-kfold
        name: efficientnet_b7-none-full-0-augs-RERUN
        reinit: true
        tags:
          - 31-class
          - kfold
          - efficientnet_b7
          - none-full
          - 0-augs
          - RERUN
