# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, ast, vit


# Ia3 
# Fourier 
# LoRA 
# AdaLoRA 
# Oft

SEND_MESSAGE: true

runs:
  - id: 1
    type: script
    changes:
      general:
        model_type: custom_cnn
        use_wandb: false
        use_sweep: false
        use_kfold: false
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        k_folds: 5
