# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over
# AST runs optimized for ESC-50 small dataset based on research findings

SEND_MESSAGE: true

runs:

  - id: 1
    type: sweep
    changes:
      general:
        model_type: custom_cnn
        from_scratch: false
        sweep_count: 9
        adapter_type: none-full
        epochs: 30
        use_wandb: true
        use_sweep: true
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      sweep:
        project: pretrained-scratch-sweeps
        name: esc50_custom_cnn_pretrained
        parameters:
          lr:
            values:
            - 1e-4
            - 1e-3
            - 1e-2
          label_smoothing:
            value: 0.1
            min: 0.0
            max: 0.2
            distribution: uniform

