# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: true


runs:
  - id: 0
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_kfold: true
        adapter_type: none-classifier
        k_folds: 5
        batch_size: 8
        epochs: 20
        learning_rate: 0.0001
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      dataset:
        dataset_type: esc50
        # data_path: /app/src/datasets/UAV_Dataset_31
        data_path: /app/src/datasets/ESC-50-master/classes
        num_classes: 50 # make sure this is correct
      feature_extraction:
        type: melspectrogram
        sampling_rate: 16000
        n_mfcc: 40
        n_mels: 128
        n_fft: 2048
        hop_length: 200
        power: 2
      augmentations:
        augmentations_per_sample: 3
      wandb:
        project: testing-esc-overfitting
        name: ast-classifier-esc50-3-augs
        reinit: true
        tags:
          - 50-class
          - kfold
          - ast
          - none-classifier
          - 3-augs