# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: true


runs:
  - id: 0
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_kfold: true
        adapter_type: ssf
        k_folds: 5
        batch_size: 8
        epochs: 30
        accumulation_steps: 2
        patience: 5
      dataset:
        dataset_type: esc50
        # data_path: /app/src/datasets/UAV_Dataset_31
        data_path: /app/src/datasets/ESC-50-master/classes
        num_classes: 50 # make sure this is correct
      feature_extraction:
        type: melspectrogram
        sampling_rate: 16000
        n_mfcc: 40
        n_mels: 128
        n_fft: 2048
        hop_length: 200
        power: 2
      optimizer:
        optimizer_type: adam
        adam:
          lr: 0.0001
          betas: [0.8, 0.98] # beta1:= momentum, beta2:= variance adaptation
        scheduler_type: cosine_annealing_lr
        cosine_annealing_lr:
          T_max: 20
          eta_min: 0.00001
        reduce_lr_on_plateau:
          mode: min
          factor: 0.85
          patience: 5
        gradient_clip_val: 5.0
        gradient_clip_algorithm: norm
      augmentations:
        augmentations_per_sample: 1
      wandb:
        project: optim-testing-esc-overfitting
        name: ast-ssf-esc50-1-augs-beta-configs
        reinit: true
  - id: 1
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_kfold: true
        adapter_type: none-full
        k_folds: 5
        batch_size: 8
        epochs: 30
        accumulation_steps: 2
        patience: 5
      dataset:
        dataset_type: esc50
        # data_path: /app/src/datasets/UAV_Dataset_31
        data_path: /app/src/datasets/ESC-50-master/classes
        num_classes: 50 # make sure this is correct
      feature_extraction:
        type: melspectrogram
        sampling_rate: 16000
        n_mfcc: 40
        n_mels: 128
        n_fft: 2048
        hop_length: 200
        power: 2
      optimizer:
        optimizer_type: adam
        adam:
          lr: 0.0001
          betas: [0.8, 0.98] # beta1:= momentum, beta2:= variance adaptation
        scheduler_type: cosine_annealing_lr
        cosine_annealing_lr:
          T_max: 20
          eta_min: 0.00001
        reduce_lr_on_plateau:
          mode: min
          factor: 0.85
          patience: 5
        gradient_clip_val: 5.0
        gradient_clip_algorithm: norm
      augmentations:
        augmentations_per_sample: 1
      wandb:
        project: optim-testing-esc-overfitting
        name: ast-none-full-esc50-1-augs-beta-configs
        reinit: true
  - id: 2
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_kfold: true
        adapter_type: none-full
        k_folds: 5
        batch_size: 8
        epochs: 30
        accumulation_steps: 2
        patience: 5
      dataset:
        dataset_type: esc50
        # data_path: /app/src/datasets/UAV_Dataset_31
        data_path: /app/src/datasets/ESC-50-master/classes
        num_classes: 50 # make sure this is correct
      feature_extraction:
        type: melspectrogram
        sampling_rate: 16000
        n_mfcc: 40
        n_mels: 128
        n_fft: 2048
        hop_length: 200
        power: 2
      optimizer:
        optimizer_type: adamw
        adamw:
          weight_decay: 0.01
          lr: 0.0001
          betas: [0.8, 0.98] # beta1:= momentum, beta2:= variance adaptation
        scheduler_type: cosine_annealing_lr
        cosine_annealing_lr:
          T_max: 20
          eta_min: 0.00001
        reduce_lr_on_plateau:
          mode: min
          factor: 0.85
          patience: 5
        gradient_clip_val: 5.0
        gradient_clip_algorithm: norm
      augmentations:
        augmentations_per_sample: 1
      wandb:
        project: optim-testing-esc-overfitting
        name: ast-none-full-esc50-1-augs-adamw
        reinit: true