# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over
# AST runs optimized for ESC-50 small dataset based on research findings

SEND_MESSAGE: true

runs:

  - id: 1
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        from_scratch: false
        batch_size: 8
        adapter_type: none-full
        epochs: 20
        patience: 15
        use_wandb: true
        use_kfold: true
        use_sweep: false
        accumulation_steps: 2
      dataset:
        dataset_type: uav
        data_path: /app/src/datasets/UAV_Dataset_31
      wandb:
        project: 31-class-kfold
        name: efficientnet_b7-full-0-augs-RERUN
        reinit: true
        tags:
          - 31-class
          - kfold
          - efficientnet_b7
          - full
          - 0-augs
          - RERUN
  - id: 2
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        from_scratch: false
        batch_size: 8
        adapter_type: none-classifier
        epochs: 20
        patience: 15
        use_wandb: true
        use_kfold: true
        use_sweep: false
        accumulation_steps: 2
      dataset:
        dataset_type: uav
        data_path: /app/src/datasets/UAV_Dataset_31
      wandb:
        project: 31-class-kfold
        name: efficientnet_b7-classifier-0-augs-RERUN
        reinit: true
        tags:
          - 31-class
          - kfold
          - efficientnet_b7
          - classifier
          - 0-augs
          - RERUN

  - id: 3
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        from_scratch: false
        batch_size: 8
        adapter_type: ssf
        epochs: 20
        patience: 15
        use_wandb: true
        use_kfold: true
        use_sweep: false
        accumulation_steps: 2
      dataset:
        dataset_type: uav
        data_path: /app/src/datasets/UAV_Dataset_31
      wandb:
        project: 31-class-kfold
        name: efficientnet_b7-ssf-0-augs-RERUN
        reinit: true
        tags:
          - 31-class
          - kfold
          - efficientnet_b7
          - ssf
          - 0-augs
          - RERUN

  - id: 4
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        from_scratch: false
        batch_size: 8
        adapter_type: batchnorm
        epochs: 20
        patience: 15
        use_wandb: true
        use_kfold: true
        use_sweep: false
        accumulation_steps: 2
      dataset:
        dataset_type: uav
        data_path: /app/src/datasets/UAV_Dataset_31
      wandb:
        project: 31-class-kfold
        name: efficientnet_b7-batchnorm-0-augs-RERUN
        reinit: true
        tags:
          - 31-class
          - kfold
          - efficientnet_b7
          - batchnorm
          - 0-augs
          - RERUN

