# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, mert, vit

SEND_MESSAGE: true

runs:

  - id: 0
    type: sweep
    changes:
      general:
        model_type: resnet18
        use_wandb: true
        use_sweep: true
        use_kfold: false
        data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
        num_classes: 31
        adapter_type: lorac
        sweep_count: 50
        epochs: 30
      sweep:
        project: resnet-experiments
        name: resnet50-none-classifer-0-augs
        method: random
        metric:
          name: test_acc
          goal: maximize
        parameters:
          learning_rate:
            values:
            - 0.1
            - 0.01
            - 0.001
          target_modules:
            values:
            - [linear,conv2d, batchnorm2d]
            - [conv2d,linear]
            - [batchnorm2d, linear]
          r: 
            values:
            - 8
            - 4
            - 2
          alpha:
            values:
            - 4
            - 8
            - 16
          dropout: 
            values:
            - 0
            - 0.1
            - 0.2
          
  - id: 1
    type: sweep
    changes:
      general:
        model_type: resnet50
      sweep:
        project: resnet-experiments
        name: resnet50-lorac-0-augs
        method: random

  - id: 2
    type: sweep
    changes:
      general:
        model_type: resnet152
      sweep:
        project: resnet-experiments
        name: resnet152-lorac-0-augs
  
  - id: 3
    type: sweep
    changes:
      general:
        model_type: resnet18
        data_path: /app/src/datasets/static/31-augs-3-time_stretch-sin_distortion
      sweep:
        project: resnet-experiments
        name: resnet18-lorac-3-augs

  - id: 4
    type: sweep
    changes:
      general:
        model_type: resnet50
      sweep:
        project: resnet-experiments
        name: resnet50-lorac-3-augs

  - id: 5
    type: sweep
    changes:
      general:
        model_type: resnet152
      sweep:
        project: resnet-experiments
        name: resnet152-lorac-3-augs
            
  
