# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, ast, vit
SEND_MESSAGE: true

runs:
  - id: 10
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets//UAV_Dataset_9
        num_classes: 9
        adapter_type: none-classifier
        k_folds: 5
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-full-kfold
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - none-classifier
      