# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: false

runs:

  - id: 0
    type: script
    changes:
      wandb:
        project: testing-metrics-kfold
        name: base-case-kfold
      general:
        model_type: resnet18
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-classifier
        sweep_count: 10
        epochs: 2
      sweep:
        project: testing-metrics
        name: resnet18-sweep-metrics
        method: random
        metric:
          name: test_acc
          goal: maximize
        parameters:
          seed:
            values:
            - 42
            - 43
            - 44
            - 45
            - 46
          learning_rate:
            values:
            - 0.001
            - 0.002
            - 0.003
            - 0.004
  
