# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over
# efficientnet_b0 runs optimized for ESC-50 small dataset based on research findings

SEND_MESSAGE: true

runs:
  # - id: 1
  #   type: script
  #   changes:
  #     general:
  #       model_type: efficientnet_b0
  #       use_wandb: true
  #       use_kfold: false
  #       adapter_type: none-full
  #       epochs: 30
  #       patience: 20
  #     dataset:
  #       dataset_type: esc50
  #       data_path: datasets/ESC-50-master/classes
  #     augmentations:
  #       augmentations_per_sample: 0
  #     peft_scheduling:
  #       enabled: true
  #       auto_merge: true
  #       schedule:
  #       - start_epoch: 25
  #         peft_method: none-classifier
  #     wandb:
  #       project: esc50-efficientnet_b0-peft-schedules
  #       name: efficientnet_b0-esc50-full-to-classifier-25
 
  - id: 7
    type: script
    changes:
      general:
        model_type: efficientnet_b0
        use_wandb: true
        use_kfold: false
        adapter_type: lorac
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b0-peft-baselines
        name: efficientnet_b0-lorac-2augs
  - id: 8
    type: script
    changes:
      general:
        model_type: efficientnet_b0
        use_wandb: true
        use_kfold: false
        adapter_type: batchnorm
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b0-peft-baselines
        name: efficientnet_b0-batchnorm-2augs
  - id: 9
    type: script
    changes:
      general:
        model_type: efficientnet_b0
        use_wandb: true
        use_kfold: false
        adapter_type: ssf
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b0-peft-baselines
        name: efficientnet_b0-ssf-2augs
  - id: 10
    type: script
    changes:
      general:
        model_type: efficientnet_b0
        use_wandb: true
        use_kfold: false
        adapter_type: none-full
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b0-peft-baselines
        name: efficientnet_b0-none-full-2augs
  - id: 11
    type: script
    changes:
      general:
        model_type: efficientnet_b0
        use_wandb: true
        use_kfold: false
        adapter_type: none-classifier
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b0-peft-baselines
        name: efficientnet_b0-none-classifier-2augs
  - id: 7
    type: script
    changes:
      general:
        model_type: efficientnet_b4
        use_wandb: true
        use_kfold: false
        adapter_type: lorac
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b4-peft-baselines
        name: efficientnet_b4-lorac-2augs
  - id: 8
    type: script
    changes:
      general:
        model_type: efficientnet_b4
        use_wandb: true
        use_kfold: false
        adapter_type: batchnorm
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b4-peft-baselines
        name: efficientnet_b4-batchnorm-2augs
  - id: 9
    type: script
    changes:
      general:
        model_type: efficientnet_b4
        use_wandb: true
        use_kfold: false
        adapter_type: ssf
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b4-peft-baselines
        name: efficientnet_b4-ssf-2augs
  - id: 10
    type: script
    changes:
      general:
        model_type: efficientnet_b4
        use_wandb: true
        use_kfold: false
        adapter_type: none-full
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b4-peft-baselines
        name: efficientnet_b4-none-full-2augs
  - id: 11
    type: script
    changes:
      general:
        model_type: efficientnet_b4
        use_wandb: true
        use_kfold: false
        adapter_type: none-classifier
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b4-peft-baselines
        name: efficientnet_b4-none-classifier-2augs
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: false
        adapter_type: lorac
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b7-peft-baselines
        name: efficientnet_b7-lorac-2augs
  - id: 8
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: false
        adapter_type: batchnorm
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b7-peft-baselines
        name: efficientnet_b7-batchnorm-2augs
  - id: 9
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: false
        adapter_type: ssf
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b7-peft-baselines
        name: efficientnet_b7-ssf-2augs
  - id: 10
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: false
        adapter_type: none-full
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b7-peft-baselines
        name: efficientnet_b7-none-full-2augs
  - id: 11
    type: script
    changes:
      general:
        model_type: efficientnet_b7
        use_wandb: true
        use_kfold: false
        adapter_type: none-classifier
        epochs: 30
        patience: 20
      dataset:
        dataset_type: esc50
        data_path: datasets/ESC-50-master/classes
      augmentations:
        augmentations_per_sample: 2
      peft_scheduling:
        enabled: false
      wandb:
        project: esc50-efficientnet_b7-peft-baselines
        name: efficientnet_b7-none-classifier-2augs