# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, ast, vit


# Ia3 
# Fourier 
# LoRA 
# AdaLoRA 
# Oft

SEND_MESSAGE: true

runs:
  - id: 0
    type: script
    changes:
      general:
        model_type: custom_cnn
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        k_folds: 5
      augmentations:
        augmentations_per_sample: 0
      wandb:
        project: DATA-2025-Presentation
        name: custom-cnn-9-kfold-0aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - custom-cnn
          - 0-aug
  - id: 1
    type: script
    changes:
      general:
        model_type: custom_cnn
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        k_folds: 5
      augmentations:
        augmentations_per_sample: 1
      wandb:
        project: DATA-2025-Presentation
        name: custom-cnn-9-kfold-0aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - custom-cnn
          - 1-aug
  - id: 2
    type: script
    changes:
      general:
        model_type: custom_cnn
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        k_folds: 5
      augmentations:
        augmentations_per_sample: 3
      wandb:
        project: DATA-2025-Presentation
        name: custom-cnn-9-kfold-0aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - custom-cnn
          - 3-aug
  - id: 3
    type: script
    changes:
      general:
        model_type: custom_cnn
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        k_folds: 5
      augmentations:
        augmentations_per_sample: 5
      wandb:
        project: DATA-2025-Presentation
        name: custom-cnn-9-kfold-0aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - custom-cnn
          - 5-aug