# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: true

runs:

  # - id: 0
  #   type: script
  #   changes:
  #     wandb:
  #       project: model-peft-test
  #       name: ast-none-classifier
  #     general:
  #       model_type: ast
  #       use_wandb: true
  #       data_path: /app/src/datasets/UAV_Dataset_9
  #       num_classes: 9
  #       adapter_type: none-classifier
  
  # - id: 1
  #   type: script
  #   changes:
  #     wandb:
  #       project: model-peft-test
  #       name: ast-none-full
  #     general:
  #       model_type: ast
  #       adapter_type: none-full

  - id: 2
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: ast-lora
      general:
        model_type: ast
        adapter_type: lora
      lora:
        r: 8

  - id: 3
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: ast-ia3
      general:
        model_type: ast
        adapter_type: ia3
  
  - id: 4
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: ast-adalora
      general:
        model_type: ast
        adapter_type: adalora
  
  - id: 5
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: ast-oft
      general:
        model_type: ast
        adapter_type: oft
  - id: 6
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: ast-layernorm
      general:
        model_type: ast
        adapter_type: layernorm
        
  - id: 7
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: ast-hra
      general:
        model_type: ast
        adapter_type: hra

      
  
  # Additional runs can be added following the same structure...
  # make sure to increment the id by 1 for each new run