# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: true


runs:
  - id: 0
    type: script
    changes:
      general:
        model_type: ast
       