# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, ast, vit


# Ia3 
# Fourier 
# LoRA 
# AdaLoRA 
# Oft

SEND_MESSAGE: true

runs:
  - id: 1
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: ia3
        k_folds: 5
      augmentations:
        augmentations_per_sample: 0
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-ia3-kfold-0aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - ia3
  - id: 2
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: ia3
        k_folds: 5
      augmentations:
        augmentations_per_sample: 1
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-ia3-kfold-1aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - ia3
  - id: 3
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: ia3
        k_folds: 5
      augmentations:
        augmentations_per_sample: 3
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-ia3-kfold-3aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - ia3
  - id: 4
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: ia3
        k_folds: 5
      augmentations:
        augmentations_per_sample: 5
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-ia3-kfold-5aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - ia3
  - id: 5
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: lora
        k_folds: 5
      augmentations:
        augmentations_per_sample: 0
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-lora-kfold-0aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - lora
  - id: 6
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: lora
        k_folds: 5
      augmentations:
        augmentations_per_sample: 1
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-lora-kfold-1aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - lora
  - id: 7
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: lora
        k_folds: 5
      augmentations:
        augmentations_per_sample: 3
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-lora-kfold-3aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - lora
  - id: 8
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: lora
        k_folds: 5
      augmentations:
        augmentations_per_sample: 5
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-lora-kfold-5aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - lora
  - id: 9
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: adalora
        k_folds: 5
      augmentations:
        augmentations_per_sample: 0
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-adalora-kfold-0aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - adalora
  - id: 10
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: adalora
        k_folds: 5
      augmentations:
        augmentations_per_sample: 1
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-adalora-kfold-1aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - adalora
  - id: 11
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: adalora
        k_folds: 5
      augmentations:
        augmentations_per_sample: 3
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-adalora-kfold-3aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - adalora
  - id: 12
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: adalora
        k_folds: 5
      augmentations:
        augmentations_per_sample: 5
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-adalora-kfold-5aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - adalora
  - id: 13
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: oft
        k_folds: 5
      augmentations:
        augmentations_per_sample: 0
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-oft-kfold-0aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - oft
  - id: 14
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: oft
        k_folds: 5
      augmentations:
        augmentations_per_sample: 1
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-oft-kfold-1aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - oft
  - id: 15
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: oft
        k_folds: 5
      augmentations:
        augmentations_per_sample: 3
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-oft-kfold-3aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - oft
  - id: 16
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: oft
        k_folds: 5
      augmentations:
        augmentations_per_sample: 5
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-oft-kfold-5aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - oft