# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, mert, vit
SEND_MESSAGE: true

runs:
# TODO update the config to work with new sweep :)
# TODO a script to make sure it works 
  # - id: 10
  #   type: script
  #   changes:
  #     general:
  #       model_type: mobilenet_v3_small
  #       use_wandb: false
  #       use_sweep: false
  #       use_kfold: false
  #       data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
  #       num_classes: 31
  #       adapter_type: none-classifier
  #       sweep_count: 30
  #       epochs: 30
  #     sweep:
  #       project: mobilenet-experiments
  #       name: mobilenet_v3_small-none-classifier-0-augs
  #       method: random
  #       metric:
  #         name: test_acc
  #         goal: maximize
  #       parameters:
  #         learning_rate:
  #           values:
  #           - 0.1
  #           - 0.01
  #           - 0.001
  #         seed:
  #           distribution: int_uniform
  #           min: 0
  #           max: 1000
          
  - id: 0
    type: sweep
    changes:
      general:
        model_type: mobilenet_v3_small
        use_wandb: true
        use_sweep: true
        use_kfold: false
        data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
        num_classes: 31
        adapter_type: none-classifier
        sweep_count: 30
        epochs: 30
      sweep:
        project: mobilenet-experiments
        name: mobilenet_v3_small-none-classifier-0-augs
        method: random
        metric:
          name: test_acc
          goal: maximize
        parameters:
          learning_rate:
            values:
            - 0.1
            - 0.01
            - 0.001
          seed:
            distribution: int_uniform
            min: 0
            max: 1000
          
  - id: 1
    type: sweep
    changes:
      general:
        model_type: mobilenet_v3_large
      sweep:
        name: mobilenet_v3_large-none-classifier-0-augs
  
  - id: 2
    type: sweep
    changes:
      general:
        model_type: mobilenet_v3_small
        data_path: /app/src/datasets/static/31-augs-3-time_stretch-sin_distortion
      sweep:
        name: mobilenet_v3_small-none-classifier-3-augs

  - id: 3
    type: sweep
    changes:
      general:
        model_type: mobilenet_v3_large
      sweep:
        name: mobilenet_v3_large-none-classifier-3-augs
  
  - id: 4
    type: sweep
    changes: 
      general:
        model_type: mobilenet_v3_small
        data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
        adapter_type: none-full
        sweep_count: 20
        epochs: 20
      sweep:
        project: mobilenet-experiments
        name: mobilenet_v3_small-none-full-0-augs
        method: random
        metric:
          name: test_acc
          goal: maximize
        parameters:
          learning_rate:
            values:
            - 0.1
            - 0.01
            - 0.001
          seed:
            distribution: int_uniform
            min: 0
            max: 1000

  - id: 5
    type: sweep
    changes: 
      general:
        model_type: mobilenet_v3_large
      sweep:
        name: mobilenet_v3_large-none-full-0-augs
        
  - id: 6
    type: sweep
    changes: 
      general:
        model_type: mobilenet_v3_small
        data_path: /app/src/datasets/static/31-augs-3-time_stretch-sin_distortion
      sweep:  
        name: mobilenet_v3_small-none-full-3-augs

  - id: 7
    type: sweep
    changes: 
      general:
        model_type: mobilenet_v3_large
      sweep:
        name: mobilenet_v3_large-none-full-3-augs

