# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: true

runs:
  - id: 0
    type: script
    changes:
      wandb:
        project: model-full-test
        name: ast
      general:
        model_type: ast
        use_wandb: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9

  - id: 1
    type: script
    changes:
      wandb:
        name: efficientnet_b0
      general:
        model_type: efficientnet_b0

  - id: 2
    type: script
    changes:
      wandb:
        name: efficientnet_b1
      general:
        model_type: efficientnet_b1

  - id: 3
    type: script
    changes:
      wandb:
        name: efficientnet_b2
      general:
        model_type: efficientnet_b2

  - id: 4
    type: script
    changes:
      wandb:
        name: efficientnet_b3
      general:
        model_type: efficientnet_b3

  - id: 5
    type: script
    changes:
      wandb:
        name: efficientnet_b4
      general:
        model_type: efficientnet_b4

  - id: 6
    type: script
    changes:
      wandb:
        name: efficientnet_b5
      general:
        model_type: efficientnet_b5

  - id: 7
    type: script
    changes:
      wandb:
        name: efficientnet_b6
      general:
        model_type: efficientnet_b6

  - id: 8
    type: script
    changes:
      wandb:
        name: efficientnet_b7
      general:
        model_type: efficientnet_b7

  - id: 9
    type: script
    changes:
      wandb:
        name: vit_b_16
      general:
        model_type: vit_b_16

  - id: 10
    type: script
    changes:
      wandb:
        name: vit_b_32
      general:
        model_type: vit_b_32

  - id: 11
    type: script
    changes:
      wandb:
        name: vit_l_16
      general:
        model_type: vit_l_16

  - id: 12
    type: script
    changes:
      wandb:
        name: vit_l_32
      general:
        model_type: vit_l_32

  - id: 13
    type: script
    changes:
      wandb:
        name: vit_h_14
      general:
        model_type: vit_h_14

  - id: 14
    type: script
    changes:
      general:
        model_type: resnet18
      wandb:
        name: resnet18

  - id: 15
    type: script
    changes:
      general:
        model_type: resnet34
      wandb:
        name: resnet34

  - id: 16
    type: script
    changes:
      general:
        model_type: resnet50
      wandb:
        name: resnet50

  - id: 17
    type: script
    changes:
      general:
        model_type: resnet101
      wandb:
        name: resnet101

  - id: 18
    type: script
    changes:
      general:
        model_type: resnet152
      wandb:
        name: resnet152

  - id: 19
    type: script
    changes:
      wandb:
        name: mobilenet_v3_small
      general:
        model_type: mobilenet_v3_small

  - id: 20
    type: script
    changes:
      wandb:
        name: mobilenet_v3_large
      general:
        model_type: mobilenet_v3_large

  - id: 21
    type: script
    changes:
      wandb:
        name: mert
      general:
        model_type: mert


  
  # Additional runs can be added following the same structure...
  # make sure to increment the id by 1 for each new run