# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, ast, vit
SEND_MESSAGE: true

runs:
  # - id: 1
  #   type: script
  #   changes:
  #     general:
  #       model_type: ast
  #       use_wandb: true
  #       use_sweep: false
  #       use_kfold: true
  #       data_path: /app/src/datasets/UAV_Dataset_9
  #       num_classes: 9
  #       adapter_type: none-full
  #       k_folds: 5
  #       augmentations_per_sample: 0
  #       augmentations:
  #       - time_stretch
  #       - sin_distortion
  #     wandb:
  #       project: DATA-2025-Presentation
  #       name: ast-9-full-kfold-0aug
  #       reinit: true
  #       tags: 
  #         - 9-class
  #         - kfold
  #         - ast
  #         - none-full
runs:
  - id: 2
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        k_folds: 5
      augmentations:
        augmentations_per_sample: 1
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-full-kfold-1aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - none-full
runs:
  - id: 3
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        k_folds: 5
      augmentations:
        augmentations_per_sample: 3
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-full-kfold-3aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - none-full
      
runs:
  - id: 4
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        k_folds: 5
      augmentations:
        augmentations_per_sample: 5
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-full-kfold-5aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - none-full
      
runs:
  - id: 5
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets//UAV_Dataset_9
        num_classes: 9
        adapter_type: none-classifier
        k_folds: 5
      augmentations:
        augmentations_per_sample: 1
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-classifier-kfold-1aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - none-classifier
runs:
  - id: 6
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets//UAV_Dataset_9
        num_classes: 9
        adapter_type: none-classifier
        k_folds: 5
      augmentations:
        augmentations_per_sample: 3
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-classifier-kfold-3aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - none-classifier
runs:
  - id: 7
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets//UAV_Dataset_9
        num_classes: 9
        adapter_type: none-classifier
        k_folds: 5
      augmentations:
        augmentations_per_sample: 5
        augmentations:
        - time_stretch
        - sin_distortion
      wandb:
        project: DATA-2025-Presentation
        name: ast-9-classifier-kfold-5aug
        reinit: true
        tags: 
          - 9-class
          - kfold
          - ast
          - none-classifier
      