# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: false

runs:

  - id: 0
    type: sweep
    changes:
      general:
        model_type: resnet152
        use_wandb: true
        use_sweep: true
        use_kfold: false
        data_path: /app/src/datasets/static/31-augs-3-time_stretch-sin_distortion
        num_classes: 31
        adapter_type: ssf
        sweep_count: 500
        epochs: 15
      sweep:
        project: 3-10-experiments
        name: resnet-ssf
        method: random
        metric:
          name: test_acc
          goal: maximize
        parameters:
          learning_rate:
            values:
            - 0.001
            - 0.005
            - 0.05
            - 0.01
          init_scale:
            values:
            - 1.0
            - 2.0
            - 0.5
          init_shift:
            values:
            - 0.0
            - 0.1
            - 0.2
            - 0.3
            - 0.4
          target_modules: 
            values:
            - [linear, conv2d, batchnorm2d]
            - [conv2d, batchnorm2d]
            - [linear, batchnorm2d]
            - [batchnorm2d]
            - [conv2d]
            
  
