# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, ast, vit


# mobilenet small, mobilenet large: none-classifier, none-full, ssf, batchnorm
# efficientnet b0, efficientnet b7: none-classifier, none-full, ssf, batchnorm

SEND_MESSAGE: true

runs:
  - id: 0
    type: script
    changes:
      general:
        model_type: mobilenet_v3_small
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31
        adapter_type: none-classifier
        k_folds: 5
        learning_rate: 0.001
        batch_size: 8
        epochs: 20
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      augmentations:
        augmentations_per_sample: 0
      wandb:
        project: 31-class-kfold
        name: mobilenet_v3_small-none-classifier-0augs-31-class-kfold
        reinit: true
        tags: 
          - 31-class
          - kfold
          - mobilenet_v3_small
          - none-classifier
          - 0-augs
  - id: 1
    type: script
    changes:
      general:
        model_type: mobilenet_v3_small
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31
        adapter_type: none-classifier
        k_folds: 5
        learning_rate: 0.001
        batch_size: 8
        epochs: 20
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      augmentations:
        augmentations_per_sample: 3
      wandb:
        project: 31-class-kfold
        name: mobilenet_v3_small-none-classifier-3augs-31-class-kfold
        reinit: true
        tags: 
          - 31-class
          - kfold
          - mobilenet_v3_small
          - none-classifier
          - 3-augs
  - id: 2
    type: script
    changes:
      general:
        model_type: mobilenet_v3_large
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31
        adapter_type: none-classifier
        k_folds: 5
        learning_rate: 0.001
        batch_size: 8
        epochs: 20
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      augmentations:
        augmentations_per_sample: 0
      wandb:
        project: 31-class-kfold
        name: mobilenet_v3_large-none-classifier-0augs-31-class-kfold
        reinit: true
        tags: 
          - 31-class
          - kfold
          - mobilenet_v3_large
          - none-classifier
          - 0-augs
  - id: 3
    type: script
    changes:
      general:
        model_type: mobilenet_v3_large
        use_wandb: true
        use_sweep: false
        use_kfold: true
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31
        adapter_type: none-classifier
        k_folds: 5
        learning_rate: 0.001
        batch_size: 8
        epochs: 20
        accumulation_steps: 2
        patience: 3
        seed: 42
        test_size: 0.2
        inference_size: 0.1
        val_size: 0.1
      augmentations:
        augmentations_per_sample: 3
      wandb:
        project: 31-class-kfold
        name: mobilenet_v3_large-none-classifier-3augs-31-class-kfold
        reinit: true
        tags: 
          - 31-class
          - kfold
          - mobilenet_v3_large
          - none-classifier
          - 3-augs