# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over


# resnet18,resnet50,resnet152, mobilenet_v3_small, mobilenet_v3_large, efficientnet_b0, efficientnet_b4, efficientnet_b7

# ast, ast, vit
SEND_MESSAGE: true

runs:
# TODO update the config to work with new sweep :)
# TODO a script to make sure it works 
  - id: 10
    type: script
    changes:
      general:
        model_type: ast
        use_wandb: false
        use_sweep: false
        use_kfold: false
        data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
        num_classes: 31
        adapter_type: ssf
        sweep_count: 50
        epochs: 30
      # ssf: #TODO configure hyperparameters
      #   init_scale: 1.0
      #   init_shift: 0.0
      #   target_modules:
      #   - linear
      #   - conv2d
      #   - batchnorm2d
  - id: 0
    type: sweep
    changes:
      general:
        model_type: ast
        use_wandb: true
        use_sweep: true
        use_kfold: false
        data_path: /app/src/datasets/static/31-augs-0-time_stretch-sin_distortion
        num_classes: 31
        adapter_type: ssf
        sweep_count: 50
        epochs: 30
      sweep:
        project: ast-experiments
        name: ast-ssf-0-augs
        method: random
        metric:
          name: test_acc
          goal: maximize
        parameters: # TODO configure hyperparameters
# ssf:
#   init_scale: 1.0
#   init_shift: 0.0
#   target_modules:
#   - linear
#   - conv2d
  # - batchnorm2d
          
  - id: 1
    type: sweep
    changes:
      general:
        model_type: ast
        data_path: /app/src/datasets/static/31-augs-3-time_stretch-sin_distortion
      sweep:
        name: ast-ssf-3-augs

  - id: 2
    type: sweep
    changes:
      general:
        model_type: ast
        data_path: /app/src/datasets/static/31-augs-5-time_stretch-sin_distortion
      sweep:
        name: ast-ssf-5-augs