# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: false

runs:
  - id: 0
    type: script
    changes:

      wandb:
        name: mobilenet_v3_small        
      general:
        model_type: mobilenet_v3_small

  - id: 1
    type: script
    changes:
      wandb:
        name: mobilenet_v3_large
      general:
        model_type: mobilenet_v3_large


 


  
  # Additional runs can be added following the same structure...
  # make sure to increment the id by 1 for each new run