# General configuration 
general:
  data_path: "/app/src/datasets/UAV_Dataset_9"
  num_classes: 9 # must match dataset
  # model_name: "AST"
  # model_name: "BERT"
  # model_name: "MERT"
  model_name: "HUBERT"
  # model_name: "WHISPER"
  batch_size: 8
  seed: 42
  num_cuda_workers: 4
  pinned_memory: true
  epochs: 20
  save_model: false
  project_name: "AST_Sweeps"
  sweep_count: 10000
  test_size: 0.2
  inference_size: 0.1
  val_size: 0.1
  shuffled : false
  accumulation_steps: 5
  learning_rate: 0.01
  patience : 3
  use_wandb: false
  
  # Augmentations Configuration (still under general config)
  augmentations_per_sample: 0
  # all currently available augmenations --> ["PitchShift", "TimeStretch", "AddGaussianNoise", "Shift", "TimeMask", "Reverse", "Normalize", "GainTransition", "PolarityInversion", "Gain"]
  augmentations: ["pitch_shift", "time_stretch"]
  # transform params must be inside list for augmentations.py to process corr
  pitch_shift_min_rate: 0
  pitch_shift_max_rate: 12.0
  pitch_shift_p: 1.0
  time_stretch_min_rate: 0.8
  time_stretch_max_rate: 1.25
  time_stretch_p: 1.0

# Script Configuration (solo run)
wandb:
  project: "AST Augmentations"
  name: "Find-tuning the best audio augmentation stack"
  reinit: false
  notes: "available options: PitchShift, TimeStretch, AddGaussianNoise, Shift, TimeMask, Reverse, Normalize, GainTransition, PolarityInversion, Gain"
  tags: "AST, "
  dir : "C:/Users/Sidewinders/Desktop/CODE/UAV_Classification_repo/notebooks/wandb"


# Sweep Configuration
sweep:
  name: "AST : pitchShift & timeStretch auto-tune"
  method: "random"
  metric:
    name: "test_acc"
    goal: "maximize"
  parameters:
    learning_rate:
      values: [0.006]
    num_augmentations:
      values: [2]
    augmentations_per_sample:
      distribution: int_uniform
      min: 1
      max: 3
    pitch_shift_min_rate:
      values: [-12.0, -9.0, -6.0, -3.0, 0]
    pitch_shift_max_rate:
      values: [0, 3.0, 6.0, 9.0, 12.0]
    time_stretch_min_rate:
      values: [0.1, 0.5, 0.8, 0.9]
    time_stretch_max_rate:
      values: [0.9, 1, 1.1, 1.25, 1.5, 1.75, 2]
