###################################
general:
  data_path: /app/src/datasets/UAV_Dataset_9
  num_classes: 9
  # model_type: CNN
  model_type: AST
  batch_size: 8
  seed: 42
  num_cuda_workers: 8
  pinned_memory: true
  epochs: 50
  save_model: false
  sweep_count: 200
  test_size: 0.2
  inference_size: 0.1
  val_size: 0.1
  shuffled: false
  accumulation_steps: 2
  learning_rate: 0.001
  patience: 5
  use_wandb: false
  torch_viz: false
  use_kfold: true
  k_folds: 5
  cnn_config:
    hidden_units: 256
    feature_extraction:
      sampling_rate: 16000
      n_mels: 128
      n_fft: 1024
      hop_length: 512
      power: 2.0
  adaptor_type: ia3
  augmentations_per_sample: 0
  augmentations:
  - time_stretch
  - sin_distortion
  time_stretch_min_rate: 0.9
  time_stretch_max_rate: 1.0
###################################
wandb:
  project: CNN H tuning
  name: ""
  reinit: false
  notes: null
  tags: null
  dir: wandb
###################################
sweep:
  name: LR Tuning
  method: random
  metric:
    name: test_acc
    goal: maximize
  parameters:
    learning_rate:
      values: [0.001, 0.002, 0.0005]
###################################
none-classifier:
  none: none
none-full:
  none: none
lora:
  r: 1000
  lora_alpha: 16
  target_modules:
  - query
  - key
  - value
  - dense
  lora_dropout: 0
  bias: lora_only
  task_type: AUDIO_CLASSIFICATION
  use_rslora: false
  use_dora: false
ia3:
  target_modules:
  - query
  - key
  - value
  - dense
  feedforward_modules:
  - dense
  - query
  - key
  - value
  task_type: AUDIO_CLASSIFICATION
adalora:
  init_r: 100
  target_r: 16
  target_modules:
  - query
  - key
  - value
  - dense
  lora_alpha: 8
  task_type: AUDIO_CLASSIFICATION
oft:
  r: 768
  target_modules:
  - query
  - key
  - value
  - dense
  module_dropout: 0.0
  init_weights: true
fourier:
  scaling: 100
  n_frequency: 1000
  target_modules:
  - query
  - key
  - value
  - dense
  task_type: AUDIO_CLASSIFICATION
layernorm:
  target_modules:
  - layernorm
  task_type: AUDIO_CLASSIFICATION
moa:
  max_length: 1024
  final_output: CLS
  reduction_rate: 128
  adapter_type: Pfeiffer
  location: MHSA
  adapter_module: bottleneck
  num_adapters: 3
soft-moa:
  max_length: 1024
  final_output: CLS
  reduction_rate: 128
  adapter_type: Pfeiffer
  location: MHSA
  adapter_module: bottleneck
  num_adapters: 3
  num_slots: 8
  normalize: true

  
