# General configuration 
general:
  data_path: "/app/src/datasets/UAV_Dataset_9"
  num_classes: 9 # must match dataset
  model_type: "AST"
  # model_type: "CNN"
  batch_size: 8
  seed: 42
  num_cuda_workers: 4
  pinned_memory: true
  epochs: 50
  save_model: false
  project_name: "9 class 5-fold Cross-Validation"
  sweep_count: 200
  test_size: 0.2
  inference_size: 0.1
  val_size: 0.1
  shuffled : false
  accumulation_steps: 2
  learning_rate: 0.006
  patience : 5
  use_wandb: false
  torch_viz: false
  use_kfold: true
  k_folds: 5  # number of folds for k-fold cross validation

  # CNN specific configurations
  cnn_config:
    hidden_units: 256  # Number of hidden units in the fully connected layer
    feature_extraction:
      sampling_rate: 16000
      n_mels: 128
      n_fft: 1024
      hop_length: 512
      power: 2.0

  # AST specific configurations
  adaptor_type: "ia3"

  # Augmentations Configuration (still under general config)
  augmentations_per_sample: 0
  augmentations: ["time_stretch", "sin_distortion"]
  
  time_stretch_min_rate: 0.9
  time_stretch_max_rate: 1.0

# Wandb configuration
wandb:
  project: "UAV_Classification"
  name: "experiment_1"
  reinit: true
  notes: "Testing model agnostic training"
  tags: ["AST", "CNN", "cross-validation"]
  dir: "wandb"


none-classifier:
  none: none

none-full:
  none: none

lora:
  r: 1000
  lora_alpha: 16
  target_modules: ["query", "key", "value", "dense"]
  lora_dropout: 0
  bias: "lora_only"
  task_type: "AUDIO_CLASSIFICATION"
  use_rslora: false
  use_dora: false

ia3:
  target_modules: ["query", "key", "value", "dense"]
  feedforward_modules: ["dense","query", "key", "value"]
  
  task_type: "AUDIO_CLASSIFICATION"

adalora:
  init_r: 100           # Initial rank
  target_r: 16            # Target rank
  target_modules: ["query", "key", "value", "dense"]
  lora_alpha: 8
  task_type: "AUDIO_CLASSIFICATION"

oft:
  r: 768
  target_modules: ["query", "key", "value", "dense"]
  module_dropout: 0.0
  init_weights: true

fourier:
  scaling: 100
  n_frequency: 1000
  target_modules: ["query", "key", "value", "dense"]
  task_type: "AUDIO_CLASSIFICATION"

layernorm:
  target_modules: ["layernorm"]  # targets all LayerNorm modules
  task_type: "AUDIO_CLASSIFICATION"

moa:
  max_length: 1024  # Example AST sequence length
  final_output: 'CLS'  # How to aggregate sequence outputs
  reduction_rate: 128   # Bottleneck reduction factor
  adapter_type: 'Pfeiffer'  # 'Pfeiffer' or 'Houlsby'
  location: 'MHSA'    # 'MHSA' or 'FFN'
  adapter_module: 'bottleneck'  # 'bottleneck' or 'conformer'
  num_adapters: 3     # Number of parallel adapters

soft-moa:
  max_length: 1024  # Example AST sequence length
  final_output: 'CLS'  # How to aggregate sequence outputs
  reduction_rate: 128   # Bottleneck reduction factor
  adapter_type: 'Pfeiffer'  # 'Pfeiffer' or 'Houlsby'
  location: 'MHSA'    # 'MHSA' or 'FFN'
  adapter_module: 'bottleneck'  # 'bottleneck' or 'conformer'
  num_adapters: 3     # Number of parallel adapters
  num_slots: 8
  normalize: True

# Sweep Configuration
sweep:
  name: "ia3 H tuning"
  method: "random"
  metric:
    name: "test_acc"
    goal: "maximize"
  parameters:
    adaptor_type:
      # values: ["ia3", "moa", "lora", "none-classifier", "none-full"]
      values: ["ia3"]
    #TODO: add H tuning params
    # r:
    #   values: [8,16,32,64]
    # module_dropout:
    #   values: [0,0.1,0.2]
    target_modules:
      values: [["query", "key", "value", "dense"]]
    feedforward_modules: 
      values: ["dense","query", "key", "value"]
    


