# config.yaml

# General configuration 
general:
  # data_path: "C:/Users/Sidewinders/Desktop/CODE/UAV_Classification_repo/src/.datasets/UAV_Dataset_9"
  data_path: "/app/src/datasets/UAV_Dataset_9"
  model_name: "MIT/ast-finetuned-audioset-10-10-0.4593"
  batch_size: 8
  seed: 42
  num_cuda_workers: 0
  num_classes: 9
  epochs: 10
  save_model: false
  project_name: "AST_Sweeps"
  sweep_count: 100
  test_size: 0.2
  inference_size: 0.1
  shuffled : true
  accumulation_steps: 3
  learning_rate: 0.001
  patience : 3
  num_train_transforms: 3
  augmentation_probability: 0.5 
  augmentations: ["PitchShift", "TimeStretch", "AddGaussianNoise", "Shift", "TimeMask", "Reverse", "Normalize", "GainTransition", "Limiter", "PolarityInversion", "Gain"]

# WandB solo run configutation (precedence over General)
wandb:
  project: "AST Fine-Tuning"
  name: "testing confusion matrix"
  reinit: false
  notes: "1st attempt at audio augmentations and normalizations"
  tags: "AST, confusion matrix"
  dir : "C:/Users/Sidewinders/Desktop/CODE/UAV_Classification_repo/notebooks/wandb"


# WandB sweep configuration
sweep:
  name: "AST_noise_test"
  method: "random"
  metric:
    goal: "maximize"
    name: "test_acc"
  parameters:
    learning_rate:
      values: [0.0001, 0.0005, 0.001, 0.005, 0.01]
    num_augmentations:
      distribution: int_uniform
      min: 0
      max: 11
