# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

runs:
  - id: 0
    type: script
    changes:
      general:
        batch_size: 16
    
  - id: 1
    type: script
    changes:
      general:
        batch_size: 8
  
  # Additional runs can be added following the same structure...