# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: false

runs:
  - id: 0
    type: script
    changes:
      wandb:
        name: CNN-0augs-LR=0.001
      general:
        batch_size: 32
        learning_rate: 0.001
        model_type: inception
        augmentations_per_sample: 0
        epochs: 100
        patience: 10
        use_wandb: false
        use_kfold: false
        data_path: /app/src/datasets/UAV_Dataset_31
        num_classes: 31


  
  # Additional runs can be added following the same structure...