# This file is used to orchestrate the sweeps and script in main.py
# Define a list of runs that can be easily iterated over

SEND_MESSAGE: false

runs:


  - id: 0
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: mert-none-classifier
      general:
        model_type: mobilenet_v3_small
        use_wandb: false
        epochs: 2
        data_path: /Users/applefella/Documents/UAV_Classification/UAV_Classification/.datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-full
        learning_rate: 0.02
  - id: 1
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: mert-none-classifier
      general:
        model_type: mobilenet_v3_small 
        use_wandb: false
        epochs: 2
        data_path: /Users/applefella/Documents/UAV_Classification/UAV_Classification/.datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: ssf
        learning_rate: 0.02
      ssf:
        target_modules:
        - linear
        - conv2d
        - batchnorm2d
  - id: 2
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: mert-none-classifier
      general:
        model_type: mobilenet_v3_small
        use_wandb: false
        epochs: 2
        data_path: /Users/applefella/Documents/UAV_Classification/UAV_Classification/.datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: batchnorm
        learning_rate: 0.02
      batchnorm:
        target_modules:
        - batchnorm2d
      
  - id: 3
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: mert-none-classifier
      general:
        model_type: mobilenet_v3_small
        use_wandb: false
        epochs: 2
        data_path: /Users/applefella/Documents/UAV_Classification/UAV_Classification/.datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-classifier
        learning_rate: 0.02
      lorac:
        target_modules:
        - linear
        - conv2d
        - batchnorm2d
        r: 8
        alpha: 8
        dropout: 0
      
  - id: 4
    type: script
    changes:
      wandb:
        project: model-peft-test
        name: mert-none-classifier
      general:
        model_type: mobilenet_v3_small
        use_wandb: false
        epochs: 2
        data_path: /Users/applefella/Documents/UAV_Classification/UAV_Classification/.datasets/UAV_Dataset_9
        num_classes: 9
        adapter_type: none-classifier
        learning_rate: 0.02
      
  